version: '3'

services:
  sync:
    image: "cskefu/sync:latest"
    restart: always
    environment:
     - DEBUG=sync*
     - NODE_ENV=${NODE_ENV:-development}
     - NOTIFY_FEISHU_GROUPS=${NOTIFY_FEISHU_GROUPS:-placeholder}
    ports:
     - "${SYNC_PORT:-8201}:8201"