version: '3'

services:
  sync:
    image: "cskefu/sync:latest"
    restart: always
    environment:
     - DEBUG=sync*
     - NODE_ENV=${NODE_ENV:-development}
     - FEISHU_GROUP_GITHUB_BOTS=${FEISHU_GROUP_GITHUB_BOTS:-placeholder}
     - FEISHU_GROUP_W3_BOTS=${FEISHU_GROUP_W3_BOTS:-placeholder}
    ports:
     - "${SYNC_PORT:-8201}:8201"